### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by y325A** [yesoreyeram/yesoreyeram-boomtable-panel#28]
Any idea how to diagnose this issue?

Is it a problem with my data or is it internal to the plugin?

```TypeError: Cannot read property 'match' of undefined
    at eval (mygrafana/grafana/public/plugins/yesoreyeram-boomtable-panel/module.js:191:53)
    at A (mygrafana/grafana/public/build/vendor.0cea50118711e7e6c839.js:1:54009)
    at fa (mygrafana/grafana/public/build/vendor.0cea50118711e7e6c839.js:1:90392)
    at Function.find (mygrafana/grafana/public/build/vendor.0cea50118711e7e6c839.js:1:79920)
    at eval (mygrafana/grafana/public/plugins/yesoreyeram-boomtable-panel/module.js:190:63)
    at Array.map (<anonymous>)
    at GrafanaBoomTableCtrl.render (mygrafana/grafana/public/plugins/yesoreyeram-boomtable-panel/module.js:189:63)
    at GrafanaBoomTableCtrl.onDataReceived (mygrafana/grafana/public/plugins/yesoreyeram-boomtable-panel/module.js:37:26)
    at o.emit (mygrafana/grafana/public/build/vendor.0cea50118711e7e6c839.js:44:25321)
    at e.emit (mygrafana/grafana/public/build/app.5372b9bbcb8c6d1c027e.js:1:13178)
```

**Comment by yesoreyeram** [comment]
It seems to be a missing data issue which was unhandled by the plugin unfortunately. What you were trying to do?

**Comment by y325A** [comment]
I was turning multiple rows into columns using the delimiter feature.

The issue seems to only happen when setting the "Override relative time" feature.

I can use the override on the InfluxDB data source, but the Azure Monitor data source seems to make it throw this exception.

**Comment by y325A** [comment]
Looks like the problem is in my data source.

Even in the default Grafana Table plugin, if no data is returned the same exception is thrown.
